version: '3.8'

services:
  onionize:
    container_name: onionize
    image: torservers/onionize
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - onion_services:/var/lib/tor/onion_services:z
    restart: unless-stopped

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    environment:
      - ONIONSERVICE_NAME=wordpress
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - db
      - onionize

  ghost:
    image: ghost:latest
    environment:
      - ONIONSERVICE_NAME=ghost
      - NODE_ENV=development
      - url=http://0.0.0.0:80
      - server__host=0.0.0.0
      - server__port=80
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - onionize
    volumes:
      - ghost_data:/var/lib/ghost

volumes:
  db_data:
  onion_services:
  ghost_data: